version: "3.8"
services:
  app:
    build:
      context: ./app
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 wsgi:flask_app 
    restart: always
    ports:
     - 5000:5000
    environment:
      - FLASK_DEBUG=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_SERIALIZER = 'pickle'
      - CELERY_ACCEPT_CONTENT = ['json', 'pickle']
      - ROLLBAR_KEY=blah
      - ROLLBAR_APP=projname
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp

  worker:
    user: nobody
    build:
      context: ./app
    command: celery -A app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_SERIALIZER = 'pickle'
      - CELERY_ACCEPT_CONTENT = ['json', 'pickle']
      - ROLLBAR_KEY=blah
      - ROLLBAR_APP=projname
    depends_on:
      - redis
    volumes:
      - /tmp:/tmp
      
  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    depends_on:
      - app

  redis:
    image: redis
