name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker-Compose Publish
      uses: pennsignals/publish_docker-compose@v0.2.6-rc.1
      with:
        docker_compose: 'docker-compose.yaml'
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
            